import type { Metadata } from 'next'
import { NextIntlClientProvider, useMessages } from 'next-intl'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function LocaleLayout({ children, params: { locale } }: { children: React.ReactNode; params: { locale: string } }) {
  const messages = useMessages()

  return (
      <NextIntlClientProvider locale={locale} messages={messages} timeZone="Asia/Seoul">
        <html lang={locale}>
            <body>{children}</body>
        </html>
      </NextIntlClientProvider>
  )
}
